# Generated by Django 2.1.10 on 2021-04-06 15:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polling', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='date_start',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 6, 15, 58, 48, 162096, tzinfo=utc), editable=False, verbose_name='Дата старта'),
        ),
    ]
