# Generated by Django 2.1.10 on 2021-04-06 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polling', '0002_auto_20210406_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='date_start',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата старта'),
        ),
    ]
