# Generated by Django 2.1.10 on 2021-04-06 17:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polling', '0004_auto_20210406_1631'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='pollquestion',
            name='count',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='Кол-во голосов'),
        ),
        migrations.AddField(
            model_name='pollquestion',
            name='question_type',
            field=models.CharField(choices=[('T', 'Text answer'), ('O', 'Question with one answer'), ('M', 'Question with many answers')], default='T', max_length=1),
        ),
        migrations.AlterField(
            model_name='poll',
            name='date_end',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 7, 17, 3, 14, 736935, tzinfo=utc), verbose_name='Дата окончания'),
        ),
    ]
