# Generated by Django 2.1.10 on 2021-04-07 11:02

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polling', '0006_auto_20210406_1712'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.CharField(default='ответ', max_length=255, verbose_name='Текст ответа')),
            ],
            options={
                'verbose_name': 'Ответ',
                'verbose_name_plural': 'Ответы',
                'ordering': ['id'],
            },
        ),
        migrations.RemoveField(
            model_name='pollquestion',
            name='count',
        ),
        migrations.AlterField(
            model_name='poll',
            name='date_end',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 8, 11, 2, 13, 843076, tzinfo=utc), verbose_name='Дата окончания'),
        ),
        migrations.AddField(
            model_name='vote',
            name='questions',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polling.PollQuestion'),
        ),
    ]
